version: '3'

services:
  rustpy-pypy:
    build:
      context: .
      args:
        - IMAGE_NAME=${PYPY_IMAGE_NAME}
        - IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/rustpy-pypy:0.0.0
    volumes:
      - ./pytest.ini:/opt/rustpy/pytest.ini
      - ./README.md:/opt/rustpy/README.md
      - ./requirements-tests.txt:/opt/rustpy/requirements-tests.txt
      - ./rustpy:/opt/rustpy/rustpy
      - ./setup.py:/opt/rustpy/setup.py
      - ./tests:/opt/rustpy/tests
    entrypoint: pytest
