version: '3'

services:
  rustpy-pypy:
    build:
      context: .
      args:
        - IMAGE_NAME=${PYPY_IMAGE_NAME}
        - IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/rustpy-pypy:0.1.0-alpha
    volumes:
      - ./pytest.ini:/opt/rustpy/pytest.ini
      - ./README.md:/opt/rustpy/README.md
      - ./rustpy:/opt/rustpy/rustpy
      - ./setup.py:/opt/rustpy/setup.py
      - ./tests:/opt/rustpy/tests
    entrypoint: pytest
